### ISSUE TITLE
Run failure possibly due to puppeteer deprecation?

### ISSUE THREAD

**Issue by hooliowobbits** [ZeanQin/strava-activities-bulk-exporter-for-garmin-connect#10]
I dunno, not a node person but
```
> npm run login

> strava-activities-bulk-exporter-for-garmin-connect@0.9.0 login
> node ./dist/index.js login

(node:3061946) UnhandledPromiseRejectionWarning: Error: Page crashed!
    at Page._onTargetCrashed (/opt/strava-activities-bulk-exporter-for-garmin-connect/node_modules/puppeteer/lib/Page.js:193:28)
    at CDPSession.<anonymous> (/opt/strava-activities-bulk-exporter-for-garmin-connect/node_modules/puppeteer/lib/Page.js:113:60)
    at CDPSession.emit (events.js:314:20)
    at CDPSession._onMessage (/opt/strava-activities-bulk-exporter-for-garmin-connect/node_modules/puppeteer/lib/Connection.js:190:18)
    at Connection._onMessage (/opt/strava-activities-bulk-exporter-for-garmin-connect/node_modules/puppeteer/lib/Connection.js:105:25)
    at WebSocket.<anonymous> (/opt/strava-activities-bulk-exporter-for-garmin-connect/node_modules/puppeteer/lib/WebSocketTransport.js:42:32)
    at WebSocket.onMessage (/opt/strava-activities-bulk-exporter-for-garmin-connect/node_modules/ws/lib/event-target.js:120:16)
    at WebSocket.emit (events.js:314:20)
    at Receiver.receiverOnMessage (/opt/strava-activities-bulk-exporter-for-garmin-connect/node_modules/ws/lib/websocket.js:801:20)
    at Receiver.emit (events.js:314:20)
(node:3061946) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:3061946) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```
and there were some deprecation warnings during install
```
> npm install
npm WARN old lockfile 
npm WARN old lockfile The package-lock.json file was created with an old version of npm,
npm WARN old lockfile so supplemental metadata must be fetched from the registry.
npm WARN old lockfile 
npm WARN old lockfile This is a one-time fix-up, please be patient...
npm WARN old lockfile 
npm WARN deprecated rimraf@3.0.2: Rimraf versions prior to v4 are no longer supported
npm WARN deprecated inflight@1.0.6: This module is not supported, and leaks memory. Do not use it. Check out lru-cache if you want a good and tested way to coalesce async requests by a key value, which is much more comprehensive and powerful.
npm WARN deprecated glob@7.1.6: Glob versions prior to v9 are no longer supported
npm WARN deprecated debug@4.1.1: Debug versions >=3.2.0 <3.2.7 || >=4 <4.3.1 have a low-severity ReDos regression when used in a Node.js environment. It is recommended you upgrade to 3.2.7 or 4.3.1. (https://github.com/visionmedia/debug/issues/797)
npm WARN deprecated @types/dotenv@8.2.0: This is a stub types definition. dotenv provides its own type definitions, so you do not need this installed.
npm WARN deprecated puppeteer@3.0.0: < 22.6.4 is no longer supported
```
I should have expected as much, repo hasn't been touched in years.  Which is fine of course, we move on.. ;)

**Comment by webbrain-one** [comment]
Hi there! Thanks for raising this. I've opened PR #12 to address it. It updates Puppeteer to a current, supported version and refreshes the dependency lockfile, which resolves the deprecation warnings and fixes the "Page crashed!" unhandled rejection. Give it a spin and let me know how it goes!
